# Generated by Django 4.2.7 on 2023-11-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_mentors_date_created_mentors_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newconvert',
            old_name='assigned_to',
            new_name='mentor',
        ),
    ]
