# Generated by Django 4.2.7 on 2023-11-07 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='unit_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
