# Generated by Django 4.2.7 on 2023-11-10 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_unit_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='cell_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
