# Generated by Django 4.2.7 on 2023-11-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_unit_date_created_unit_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('males', models.IntegerField(blank=True, null=True)),
                ('females', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('vehicles', models.IntegerField(blank=True, null=True)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.attendance')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='CountingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.unit')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='counting_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.countingunit'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.servicetime'),
        ),
    ]
