# Generated by Django 4.2.7 on 2023-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_service_attendance_service_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='service_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='attendance',
            field=models.ManyToManyField(to='management.attendance'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
