# Generated by Django 4.2.7 on 2023-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_attendance_first_timers_attendance_new_converts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_timers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='new_converts',
            field=models.IntegerField(default=0),
        ),
    ]
