# Generated by Django 4.2.7 on 2023-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_service_message_remove_service_minister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='minister',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
