# Generated by Django 4.2.7 on 2023-11-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_attendance_message_alter_attendance_minister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering', models.IntegerField(blank=True)),
                ('tithe', models.IntegerField(blank=True)),
                ('thanksgiving', models.IntegerField(blank=True)),
                ('shilo_sacrifice', models.IntegerField(blank=True)),
                ('projects', models.IntegerField(blank=True)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('service_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.servicetime')),
            ],
        ),
    ]
