# Generated by Django 4.2.7 on 2023-11-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_service_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='offering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='projects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='shilo_sacrifice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='thanksgiving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='tithe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
