# Generated by Django 4.2.7 on 2023-11-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_income_offering_alter_income_projects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='shilo_sacrifice',
            new_name='shiloh_sacrifice',
        ),
    ]
