# Generated by Django 4.2.7 on 2023-11-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rename_shilo_sacrifice_income_shiloh_sacrifice'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='management.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='attendance', to='management.attendance'),
        ),
    ]
