# Generated by Django 4.2.7 on 2023-11-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_service_attendance_remove_service_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='service_type',
        ),
    ]
