# Generated by Django 4.2.7 on 2023-11-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_income_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='service_type',
        ),
    ]
