# Generated by Django 4.2.7 on 2023-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='baptized',
            field=models.BooleanField(default=False),
        ),
    ]
